### PR TITLE
Add Outreach Team meeting minutes from 2021-06-07

### PR DESCRIPTION
**Pull request by seabass-labrax**
Minutes taken by Joshua Marpet and Sebastian Crane

### CODE REVIEW

**Comment by seabass-labrax** [comment]
To be merged upon approval at next Outreach Team meeting

**Comment by seabass-labrax** [comment]
Minutes approved at SPDX Outreach team meeting on 2021-06-14.

**Comment by swinslow** [comment]
Thank you @seabass-labrax! Merging now.

**Comment by seabass-labrax** [comment]
Thanks for merging :)

**Pull request merged**
