### PR TITLE
Create 2023-12-05.md

### PR DESCRIPTION
**Pull request by robcraig-LF**
Adds minutes and agenda SPDX Tech Team Meeting 2023-12-05

### CODE REVIEW

**Review by goneall — CHANGES_REQUESTED** [review]
@robcraig-LF If you could rename this file to 2023-12-05.md and all other pull requests using the same naming conventions.

**Comment by robcraig-LF** [comment]
Sorry about that Gary.
-Rob

Rob Craig
Standards Program Manager
Strategic Programs
Time zone: GMT-4 (NJ/USA)
+1.201.455.7044
Overture Maps <https://overturemaps.org/> | SPDX <https://spdx.dev/>
Book time to meet with me! <https://calendar.app.google/k6bBwvgs7xe4brq36>
github.com/robcraig-LF

**Comment by goneall** [comment]
@zvr - can you review and if OK, merge since I wasn't at this meeting?

**Review by goneall — APPROVED** [review]
LGTM

**Pull request merged**
