### PR TITLE
add operations meeting notes 2024-10-11, add legacy meeting notes 

### PR DESCRIPTION
**Pull request by umm0**
add operation profile meeting notes for 2024-10-11 and legacy meeting notes from existing etherpad

### CODE REVIEW

**Comment by goneall** [comment]
@umm0 - Normally we have a second reviewer before merging the notes - but since this is catching up on some previous notes let me know if you want me to just merge this in.

**Comment by umm0** [comment]
Thank you @goneall for the offer. I already posted the pull request to our e-mail list in case anyone wants to review it. 
I will give it a few days.

**Comment by bact** [comment]
May be it's a good idea to put all the 2024 minutes inside `2024/` subdirectory, so in 2025 we don't have to move them later.

**Comment by umm0** [comment]
I followed https://github.com/spdx/meetings/blob/main/CONTRIBUTING.md:

> Meeting minutes are titled by the date in the format YYYY-MM-DD.md. At the end of the year, that year's files should be moved into a directory named for that year YYYY.

Therefore I would only move the files into `2024` subdirectory at the end of this year. 

But I don't have strong feelings either way. I would also be fine with having a `2024` subdirectory now.

**Comment by bact** [comment]
You're right. The contributing said that.

Also find that with a backlog of PRs waiting for merging, it can take two or three years or more until all the meetings from a year X will go to the X/ folder, as some of them got merged late and went into the root level (and have to open another set of PRs to gradually move all of them).

Another issue is cross-referencing (from within this repo and from elsewhere), when files are moved, we have to update the links as well. (Possible to get done, but take some effort).

I will open an issue discussing this if we can update our contributing guidelines. Thank you for reminding me of this.

**Comment by umm0** [comment]
In the Operations meeting 2024-10-18 talked about this and were fine with either adding a YYYY subfolder or not.
Following @bact 's reasoning in the comment above I now moved the meeting notes to a '2024' subfolder.

I also added the notes for 2024-10-18 to save an extra pull request.

**Comment by umm0** [comment]
Meeting notes from operations meeting 2024-10-25 added.
Marcel will add a comment here, when he agrees with the pull request. I don't think I have the necessary rights to add him as a reviewer.

**Review by mkurzman — APPROVED** [review]
Thank you Ummo, please proceed with the merge.

**Comment by umm0** [comment]
Hi @goneall can you merge the pull request?
I don't have the necessary permission. 

Thank you.

**Pull request merged**
