### PR TITLE
Add AI minutes 2024-05-22

### PR DESCRIPTION
**Pull request by bact**
Adds meeting minutes and agenda from SPDX AI Team Meeting 2024-05-22

### CODE REVIEW

**Review by bennetkl — COMMENTED** [review]
Approved, ready to merge

**Comment by bennetkl** [comment]
Merge

**Comment by bact** [comment]
@bennetkl you probably accidentally closed this PR.

**Comment by bact** [comment]
We have to reopen this. The minutes is not recorded to the main repo yet.

**Comment by bennetkl** [comment]
reopen

**Pull request merged**
