### PR TITLE
Add Outreach Team meeting minutes from 2021-06-21

### PR DESCRIPTION
**Pull request by seabass-labrax**
Minutes taken by Sebastian Crane

### CODE REVIEW

**Comment by seabass-labrax** [comment]
To be merged upon approval at next Outreach Team meeting.

**Comment by seabass-labrax** [comment]
Minutes approved at SPDX Outreach Team meeting on 2021-06-28.

**Comment by swinslow** [comment]
Merged!

**Comment by swinslow** [comment]
Also, @seabass-labrax I just sent you an invite with write access to this repo, so that you'll be able to merge outreach team minutes going forward, if you're good with that?

**Comment by seabass-labrax** [comment]
Thank you; I've accepted the invite. Thanks also for taking the time to merge my previous pull requests! :)

**Pull request merged**
