### PR TITLE
Create 2023-11-08.md

### PR DESCRIPTION
**Pull request by robcraig-LF**
Adds meeting minutes and agenda SPDX AI Team Meeting 2023-11-08

### CODE REVIEW

**Comment by bennetkl** [comment]
Minutes approved.

**Comment by bennetkl** [comment]
Approved, can close this pull request

**Review by bennetkl — APPROVED** [review]
Minutes approved

**Review by bennetkl — APPROVED** [review]
Minutes approved.

**Comment by goneall** [comment]
@bennetkl did you want the closed or merged?  From your comments it looks like it should be merged and not closed without merging.  @robcraig-LF closed without merging - I'll re-open until I hear from you.

**Pull request merged**
