### PR TITLE
Create 2023-06-06.md

### PR DESCRIPTION
**Pull request by robcraig-LF**
Adds meeting minutes from Tech meeting

### CODE REVIEW

**Comment by goneall** [comment]
@robcraig-LF When I create the minutes PR's, I also update the [decisions.md](https://github.com/spdx/meetings/blob/main/tech/decisions.md) file if anything is clearly marked as a decision.  Could you also update?

I usually do the decisions update as a separate PR and sometimes batch a couple of meeting decisions to avoid merge conflicts.

**Comment by robcraig-LF** [comment]
Understood. I will review and update as per your request.

**Comment by robcraig-LF** [comment]
As I'm new to SPDX - I am very hopeful you and Kate can help me on this so that we can create an efficient process. It would be helpful if when we are recording minutes we clearly indicate a DECISION. In reviewing previous minutes and cross referencing them against the DECISIONS list, it isn't entirely clear if a discussion resulted in a decision (or if it was rather more a fact-finding endeavor).

**Comment by goneall** [comment]
> I am very hopeful you and Kate can help me on this so that we can create an efficient process. It would be helpful if when we are recording minutes we clearly indicate a DECISION. 

@robcraig-LF - good point, we don't have a formal way of denoting decisions in the minutes.  I've been marking them with a clear "DECISION: ", but I don't know if we've been consistent about that.  We should raise this on the next call so it is a common practice.

The other think I try to do when I'm facilitating is to make it very clear verbally that we are making a decisions.  It is very common the discussion moves onto other topics when a decisions is implicit and we don't have enough clarity to mark it as a decision.

One other consideration is the granularity of the decisions we want to record in the decisions table.  I tend to only record bigger decisions - not necessarily all decisions.  We can use the process of only marking "DECISION" in the minutes for the bigger decisions that we want to record in the table.

**Comment by goneall** [comment]
@robcraig-LF - In the minutes there is a "DECISION: " bullet - if you could add that to the decisions table.

**Pull request merged**
